# This contains the steps used when building the app(Include signing)
jobs:
  - job: Linux
    pool:
      name: Azure-Pipelines-EO-Batch-Explorer
      demands:
      - ImageOverride -equals BatchExplorerBuildImage-Linux
    steps:
       - template: ./linux/distribution.yml

  - job: MacOS
    pool:
      vmImage: macOS-11
      demands: xcode
    variables:
      - name: EOCompliance-Mac
        value: true
    steps:
       - template: ./darwin/distribution.yml

  - job: Windows
    pool:
      name: Azure-Pipelines-EO-Batch-Explorer
      demands:
      - ImageOverride -equals BatchExplorerBuildImage-Windows
    steps:
      - template: ./win/distribution.yml
