stages:
  - stage: Localization
    jobs:
      - job:
        pool:
          name: Azure-Pipelines-EO-Batch-Explorer
          demands:
          - ImageOverride -equals BatchExplorerBuildImage-Windows
        steps:
          - task: OneLocBuild@2
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            inputs:
              locProj: 'Localize/LocProject.json'
              outDir: '$(Build.ArtifactStagingDirectory)'
              dependencyPackageSource: 'https://azurebatch.pkgs.visualstudio.com/_packaging/BatchExplorer/nuget/v3/index.json'
              packageSourceAuth: 'patAuth'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Build
    dependsOn: Localization
    condition: succeeded('Localization')
    jobs:
      - job: DownloadArtifacts
        pool:
          name: Azure-Pipelines-EO-Batch-Explorer
          steps:
            - download: current
              artifact: drop

      - job: Linux
        dependsOn: DownloadArtifacts
        pool:
          name: Azure-Pipelines-EO-Batch-Explorer
          demands:
          - ImageOverride -equals BatchExplorerBuildImage-Linux
        steps:
          - template: ./linux/distribution.yml

          - script: |
              set -e
              changed=`git status | grep 'modified:' | wc -l`
              if [ "$changed" -ne "0" ]; then
                echo "Changes detected. Pipeline failed"
                exit 1
              fi
            workingDirectory: $(Build.ArtifactStagingDirectory)/BatchExplorer
            displayName: Validate no files changed on build

      - job: MacOS
        dependsOn: DownloadArtifacts
        pool:
          vmImage: macOS-11
          demands: xcode
        variables:
          - name: EOCompliance-Mac
            value: true
        steps:
          - template: ./darwin/distribution.yml

      - job: Windows
        dependsOn: DownloadArtifacts
        pool:
          name: Azure-Pipelines-EO-Batch-Explorer
          demands:
          - ImageOverride -equals BatchExplorerBuildImage-Windows
        steps:
          - template: ./win/distribution.yml
