stages:
  - stage: Localization
    jobs:
      - job:
        pool:
          name: Azure-Pipelines-EO-Batch-Explorer
          demands:
          - ImageOverride -equals BatchExplorerBuildImage-Windows
        steps:
          - task: OneLocBuild@2
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            inputs:
              locProj: 'Localize/LocProject.json'
              outDir: '$(Build.ArtifactStagingDirectory)'
              dependencyPackageSource: 'https://azurebatch.pkgs.visualstudio.com/_packaging/BatchExplorer/nuget/v3/index.json'
              packageSourceAuth: 'patAuth'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Build
    dependsOn: Localization
    condition: succeeded('Localization')
    jobs:

      - job: Linux
        timeoutInMinutes: 120 # Needed for Codesign + CodeQL
        pool:
          name: Azure-Pipelines-EO-Batch-Explorer
          demands:
          - ImageOverride -equals BatchExplorerBuildImage-Linux
        steps:
          - template: ./linux/distribution.yml

      - job: MacOS
        timeoutInMinutes: 120 # Needed for Codesign + Notarization + CodeQL
        pool:
          vmImage: macOS-13
          demands: xcode
        variables:
          - group: BatchExplorer-Signing
          - name: EOCompliance-Mac
            value: true
        steps:
          - template: ./darwin/distribution.yml

      - job: Windows
        timeoutInMinutes: 120 # Needed for Codesign + CodeQL
        pool:
          name: Azure-Pipelines-EO-Batch-Explorer
          demands:
          - ImageOverride -equals BatchExplorerBuildImage-Windows
        steps:
          - template: ./win/distribution.yml
