# This contains the steps used when building the app(Include signing)
jobs:
  - job: Linux
    pool: Hosted Linux Preview
    steps:
       - template: ./linux/distribution.yml

  - job: MacOS
    pool: Hosted macOS
    steps:
       - template: ./darwin/distribution.yml

  - job: Windows
    pool: Hosted VS2017
    steps:
      - template: ./win/distribution.yml
