name: $(SourceBranch)$(Rev:.r)
jobs:
  - job: Linux
    pool:
      name: Azure-Pipelines-EO-Batch-Explorer
      demands:
        - ImageOverride -equals BatchExplorerBuildImage-Linux
    steps:
      - template: ./linux/ci.yml

  - job: MacOS
    pool:
      vmImage: macOS-13
      demands: xcode
    variables:
      - name: EOCompliance-Mac
        value: true
    steps:
      - template: ./darwin/ci.yml

  - job: Windows
    pool:
      name: Azure-Pipelines-EO-Batch-Explorer
      demands:
        - ImageOverride -equals BatchExplorerBuildImage-Windows
    variables:
      Packaging.EnableSBOMSigning: true
    steps:
      - template: ./win/ci.yml

  - job: Test
    pool:
      name: Azure-Pipelines-EO-Batch-Explorer
      demands:
        - ImageOverride -equals BatchExplorerBuildImage-Linux
    steps:
       - template: ./linux/test.yml
