name: $(SourceBranch)$(Rev:.r)
jobs:
  - job: Linux
    pool: Hosted Linux Preview
    # pool:
      # vmImage: ubuntu-16.04
    steps:
       - template: ./linux/ci.yml

  - job: MacOS
    pool:
      vmImage: xcode9-macos10.13
    steps:
       - template: ./darwin/ci.yml

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: ./win/ci.yml

  - job: RegisterDependencies
    displayName: Register dependencies
    pool:
      vmImage: vs2017-win2016
    condition: ne(variables['Build.Reason'], 'PullRequest')
    continue_on_error: true
    steps:
      - template: ./dependencies.yml
      - script: npm ci
      - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
        displayName: 'Component Detection'
        # inputs:
        #   governanceProduct: '395dd579-66b8-e811-af11-00155d7ffd9f'

