name: $(SourceBranch)$(Rev:.r)
jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
       - template: ./linux/ci.yml

  - job: MacOS
    pool:
      vmImage: xcode9-macos10.13
    steps:
       - template: ./darwin/ci.yml

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: ./win/ci.yml

  - job: RegisterDependencies
    displayName: Register dependencies
    pool:
      vmImage: vs2017-win2016
    condition: ne(variables['Build.Reason'], 'PullRequest')
    variables:
      EnableDetectorPip: true
    continueOnError: true
    steps:
      - template: ./win/win-dependencies.yml
      - task: ComponentGovernanceComponentDetection@0
        displayName: 'Component Detection'
