name: $(SourceBranch)$(Rev:.r)
jobs:
  - job: Linux
    pool: Hosted Linux Preview
    steps:
    - template: ./linux/ci.yml

  # Mac os build
  - job: MacOS
    pool: Hosted macOS Preview
    steps:
    - template: ./linux/ci.yml

  - job: Windows
    pool: Hosted VS2017
    steps:
      - template: ./windows/ci.yml
