name: $(SourceBranch)$(Rev:.r)
jobs:
  - job: Linux
    pool:
      name: Azure-Pipelines-EO-Batch-Explorer
      demands:
        - ImageOverride -equals BatchExplorerBuildImage-Linux
    steps:
      - template: ./linux/ci.yml

  - job: MacOS
    pool:
      vmImage: macOS-10.15
      demands: xcode
    variables:
      - name: EOCompliance-Mac
        value: true
    steps:
      - template: ./darwin/ci.yml

  - job: Windows
    pool:
      name: Azure-Pipelines-EO-Batch-Explorer
      demands:
        - ImageOverride -equals BatchExplorerBuildImage-Windows
    steps:
      - template: ./win/ci.yml

  - job: RegisterDependencies
    displayName: Register dependencies
    pool:
      name: Azure-Pipelines-EO-Batch-Explorer
      demands:
        - ImageOverride -equals BatchExplorerBuildImage-Windows
    condition: ne(variables['Build.Reason'], 'PullRequest')
    variables:
      EnableDetectorPip: true
    continueOnError: true
    steps:
      - template: ./win/win-dependencies.yml
      - task: ComponentGovernanceComponentDetection@0
        displayName: "Component Detection"
