name: $(SourceBranch)$(Rev:.r)
jobs:
  - job: Linux
    pool:
      # vmImage: ubuntu-16.04
      vmImage: Hosted Linux Preview
    steps:
       - template: ./linux/ci.yml

  - job: MacOS
    pool:
      vmImage: xcode9-macos10.13
    steps:
       - template: ./darwin/ci.yml

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: ./win/ci.yml
