export const DeprecatedContainerImages = [
    "2016-datacenter-with-containers",
    "2016-datacenter-with-containers-g2",
    "2016-datacenter-with-containers-gs",
    "2019-datacenter-core-with-containers",
    "2019-datacenter-core-with-containers-g2",
    "2019-datacenter-core-with-containers-smalldisk",
    "2019-datacenter-core-with-containers-smalldisk-g2",
    "2019-datacenter-with-containers",
    "2019-datacenter-with-containers-g2",
    "2019-datacenter-with-containers-gs",
    "2019-datacenter-with-containers-smalldisk",
    "2019-datacenter-with-containers-smalldisk-g2",
    "datacenter-core-20h2-with-containers-smalldisk",
    "datacenter-core-20h2-with-containers-smalldisk-gs",
    "datacenter-core-20h2-with-containers-smalldisk-g2",
];
