settings:
  title: Settings
  saved: Saved
  general: General
  advancedSettings: Advanced settings
  gallerySettings: Gallery settings
  reset: Reset to default settings
  external-browser-auth: Use system browser for authentication
  external-browser-auth-hint: Organizations with certain access policies may require sign-in with an internal window. Unset if you experience issues.
