export const COMMAND_LABEL_ICON = {
    AddJob: { label: "Add job", icon: "fa fa-plus" },
    AddTask: { label: "Add task", icon: "fa fa-plus" },
    AddApplication: { label: "Add package", icon: "fa fa-plus" },
    AddFile: {  label: "Add more files to the file group", icon: "fa fa-plus" },
    Delete: { label: "Delete", icon: "fa fa-trash-o" },
    ExportAsJSON: { label: "Export as JSON", icon: "fa fa-code" },
    Terminate: { label: "Terminate", icon: "fa fa-stop" },
    Edit: { label: "Edit", icon: "fa fa-edit" },
    EditStartTask: { label: "Edit start task", icon: "fa fa-pencil-square-o" },
    Resize: { label: "Resize", icon: "fa fa-arrows-v" },
    Clone: { label: "Clone", icon: "fa fa-clone" },
    Enable: { label: "Enable", icon: "fa fa-play" },
    Disable: { label: "Disable", icon: "fa fa-pause" },
    CreateJobScheduleForJobs: { label: "Create job schedule for this job", icon: "fa fa-calendar" },
    Credentials: { label: "Credentials and code samples", icon: "fa fa-key" },
    ConnectToNode: { label: "Connect", icon: "fa fa-plug" },
    RebootNode: { label: "Reboot", icon: "fa fa-power-off" },
    Reactivate: { label: "Reactivate", icon: "fa fa-undo" },
    Download: { label: "Download", icon: "fa fa-download" },
    UnpinFavoriteLabel: "Unpin favorite",
    PinFavoriteLabel: "Pin to favorites",
    UnpinFavoriteIcon: "fa fa-chain-broken",
    PinFavoriteIcon: "fa fa-link",
};
